In [2]:
import pandas as pd

In [3]:
movies = pd.read_csv("../dataset/movies.csv")

In [4]:
print(movies.head())

      id                        title                 genre original_language  \
0    278     The Shawshank Redemption           Drama,Crime                en
1  19404  Dilwale Dulhania Le Jayenge  Comedy,Drama,Romance                hi
2    238                The Godfather           Drama,Crime                en
3    424             Schindler's List     Drama,History,War                en
4    240       The Godfather: Part II           Drama,Crime                en

                                            overview  popularity release_date  \
0  Framed in the 1940s for the double murder of h...      94.075   1994-09-23
1  Raj is a rich, carefree, happy-go-lucky second...      25.408   1995-10-19
2  Spanning the years 1945 to 1955, a chronicle o...      90.585   1972-03-14
3  The true story of how businessman Oskar Schind...      44.761   1993-12-15
4  In the continuing saga of the Corleone crime f...      57.749   1974-12-20

   vote_average  vote_count
0           8.7       21862
1           8.7        3731
2           8.7       16280
3           8.6       12959
4           8.6        9811

In [5]:
print(movies.shape)

(10000, 9)

In [6]:
print(movies.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  str
 2   genre              9997 non-null   str
 3   original_language  10000 non-null  str
 4   overview           9987 non-null   str
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  str
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 703.3 KB
None

In [7]:
print(movies.describe())

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [8]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

Feature Selection Part

In [9]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='str')

In [10]:
movies = movies[["id", "title", "genre", "overview"]]
movies

,id,title,genre,overview
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

In [11]:
movies["tags"] = movies["overview"] + " " + movies["genre"]
movies

,id,title,genre,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second...","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...
...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo...","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"Action,Science Fiction,War","During World War II, a brave, patriotic Americ...","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...,Seeking justice for his partner’s murder by an...

In [12]:
new_data = movies.drop(columns=["overview", "genre"])
new_data

,id,title,tags
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...
...,...,...,...
9995,10196,The Last Airbender,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,Seeking justice for his partner’s murder by an...

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
vectorizer = TfidfVectorizer(max_features=10000, stop_words='english')

In [15]:
vector = vectorizer.fit_transform(movies["tags"].values.astype('U')).toarray()

In [16]:
vector.shape

(10000, 10000)

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.01620084, 0.02667563, ..., 0.0602474 , 0.04669491,
        0.03041582],
       [0.01620084, 1.        , 0.01158987, ..., 0.        , 0.00355575,
        0.        ],
       [0.02667563, 0.01158987, 1.        , ..., 0.01236133, 0.02225019,
        0.02298144],
       ...,
       [0.0602474 , 0.        , 0.01236133, ..., 1.        , 0.00652407,
        0.00554288],
       [0.04669491, 0.00355575, 0.02225019, ..., 0.00652407, 1.        ,
        0.0094767 ],
       [0.03041582, 0.        , 0.02298144, ..., 0.00554288, 0.0094767 ,
        1.        ]], shape=(10000, 10000))

In [19]:
new_data[new_data["title"]=="The Godfather"].index[0]

2

In [20]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
The Godfather: Part III
Blood Ties
The Best of Youth

In [21]:
def recommend(movie):
    index = new_data[new_data["title"]==movie].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [22]:
recommend("Iron Man")

Iron Man
Iron Man 2
Iron Man 3
Clown
Avengers: Age of Ultron